### ISSUE TITLE
AttributeError: module 'genpy' has no attribute 'Duration'

### ISSUE THREAD

**Issue by bahadirozkan** [manasrda/ros_numpy#3]
Hello, does this work with the Humble? When I run the example script for PointCloud2 in the Readme I'm getting "AttributeError: module 'genpy' has no attribute 'Duration'. Did you mean: 'Function'?". I didn't see a genpy package for Humble.

**Comment by manasrda** [comment]
@bahadirozkan 
Humble is ROS 2. At the moment, I beleive this doesn't support ROS2 and there are no plans to do so.
