### ISSUE TITLE
Deprecation Issues from Numpy

### ISSUE THREAD

**Issue by olanrewajufarooq** [manasrda/ros_numpy#4]
While I was using Open3D (which uses ros_numpy as a dependency), I observed an error which was due to a deprecation in numpy. The error details is as follows:

> AttributeError                            Traceback (most recent call last)
----> [1] from open3d_ros_helper import open3d_ros_helper as orh
      [3]rospc = orh.o3dpc_to_rospc(point_cloud)
File [.../open3d_ros_helper/open3d_ros_helper.py:1)
----> [1]import ros_numpy
      [2]import open3d
      [3] import numpy as np
File [.../ros_numpy/__init__.py:7]
      [5]from .numpy_msg import numpy_msg
      [6]from .registry import numpify, msgify
----> [7]from . import point_cloud2
      [8]from . import image
      [9]from . import occupancy_grid
File [.../ros_numpy/point_cloud2.py:224)
    [221] new_cloud_arr[field_name] = cloud_arr[field_name]
    [222]return new_cloud_arr
--> [224]def get_xyz_points(cloud_array, remove_nans=True, dtype=np.float):
    [225]'''Pulls out x, y, and z columns from the cloud recordarray, and returns
    [226]a 3xN matrix.
    [227]'''
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations... 

I presume that this might be an issue that would require a wholesome code refactoring to fix. Can this be amended?

**Comment by manasrda** [comment]
@olanrewajufarooq 
Haven't been checking this for some time. Updated!
